# Generated by Django 4.0.3 on 2022-03-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='فاعل خير', max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('wilaya', models.CharField(max_length=200)),
                ('commun', models.CharField(max_length=200)),
                ('zomra', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('AB+', 'AB+'), ('A-', 'A-'), ('AB-', 'AB-')], max_length=3)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
